name: milktriformer-milk10k
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pytorch
  - torchvision
  - pytorch-cuda=12.1
  - numpy
  - pandas
  - pillow
  - scikit-learn
  - pytest
  - pip:
      - timm>=0.9.12
